version: '3'
services:
  # db:
  #   image: postgres:13.2-alpine
  #   environment:
  #     TZ: UTC
  #     PGTZ: UTC
  #     POSTGRES_PASSWORD: $DATABASE_PASSWORD
  #   volumes:
  #     - ./backend/tmp/db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
  # #   command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  # #   environment:
  # #     DATABASE_HOST: $DATABASE_HOST
  # #     DATABASE_USERNAME: $DATABASE_USERNAME
  # #     DATABASE_PASSWORD: $DATABASE_PASSWORD
  # #     FRONTEND_DOMAIN: "localhost:$FRONTEND_PORT"
  # #     BACKEND_URL: "http://localhost:$BACKEND_PORT"   
    volumes:
      - .:/go/src/app
  #   links:
  #     - db
    ports:
      - "$BACKEND_PORT:$CONTAINER_PORT"

  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        BACKEND_URL: "http://localhost:$BACKEND_PORT"
    volumes:
      - ./frontend:/$WORKDIR
    command: yarn dev
    ports:
      - "$FRONTEND_PORT:$CONTAINER_PORT"
    # depends_on:
    #   - backend
